name: Main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Parse terraform version"
        id: tf_version
        uses: ministryofjustice/opg-github-actions/.github/actions/terraform-version@v2.3.1
        with:
          terraform_directory: "./"
      - name: "Setup terraform [version: ${{ steps.tf_version.outputs.version }}]"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.tf_version.outputs.version }}
      - name: terraform fmt
        run: |
          terraform fmt -check -recursive

  versioning:
    name: Bump Version
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: "Generate semver tag and release"
        id: semver_tag
        uses: ministryofjustice/opg-github-actions/.github/actions/semver-tag@v3.0.6
        with:
          prerelease: ${{ github.ref != 'refs/heads/main' }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
